- hosts: centos
  become: false 
  tasks:
  -  name: check connection
     ping:
  -  name: Update OS
     yum:
       name: '*'
       state: latest
  -  name: Copy file
     copy:
       src: demo.txt
       dest: /tmp/demo.txt       