- hosts: centos
  become: false 
  vars:
    Greeting: hello_now
  tasks:
  -  name: check connection
     ping:
  -  name: Update OS
     yum:
       name: '*'
       state: latest
  -  name: Copy file
     copy:
       src: demo.txt
       dest: /tmp/demo.txt
  -  name: echo
     command: echo 'set {{Greeting}} to this'
   